// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeMessage is the Wire injector function.
func InitializeMessage() *Message {
	config := NewConfig()
	greeter := NewGreater(config)
	message := NewMessage(greeter)
	return message
}
