// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"wire-providerset/internal/config"
	"wire-providerset/internal/greeter"
	"wire-providerset/internal/message"
)

// Injectors from injector.go:

func InitializeDependency() *message.Message {
	configConfig := config.NewConfig()
	greeterGreeter := greeter.NewGreeter(configConfig)
	messageMessage := message.NewMessage(greeterGreeter)
	return messageMessage
}

// injector.go:

var providerSet = wire.NewSet(config.ProviderSet, greeter.ProviderSet, message.ProviderSet)
